# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: false

reviewers:
  - leesungbin
  - yeynii
  - Palwol
  - JunYupK

numberOfReviewers: 2
