version: "3"

services:
  prv:
    restart: always
    env_file:
      - ${ENV_FILE}
    image: ${NCP_CONTAINER_REGISTRY}/prv-backend
    links:
      - redis
      - mongo
    ports:
      - 4000:4000
    networks:
      - viewpoint

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - viewpoint

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - viewpoint

  client:
    image: ${NCP_CONTAINER_REGISTRY}/prv-frontend
    ports:
      - 3000:80

networks:
  viewpoint:
    driver: bridge
