name: "Frontend Tester"
on:
  pull_request:
    types: [opened, ready_for_review]
    paths:
      - "frontend/**"

jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: FE Test - ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd frontend
          npm ci
          npm test
