name: Production Deploy(BE)

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  push_to_registry_be:
    name: (BE) Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx 1
        uses: docker/setup-buildx-action@v2
      - name: Login to NCP Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.PRODUCTION_CONTAINER_REGISTRY }}
          username: ${{ secrets.PRODUCTION_ACCESS_KEY }}
          password: ${{ secrets.PRODUCTION_SECRET_KEY }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.PRODUCTION_CONTAINER_REGISTRY }}/prv-backend:latest
            ${{ secrets.PRODUCTION_CONTAINER_REGISTRY }}/prv-backend:${{ github.run_number }}
          cache-from: type=registry,ref=${{ secrets.PRODUCTION_CONTAINER_REGISTRY }}/prv-backend:latest
          cache-to: type=inline

  pull_from_registry:
    name: Connect server ssh and pull from container registry
    needs: push_to_registry_be
    runs-on: ubuntu-latest
    steps:
      - name: connect ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_BE_HOST }}
          username: ${{ secrets.PRODUCTION_BE_USERNAME }}
          password: ${{ secrets.PRODUCTION_BE_PASSWORD }}
          port: ${{ secrets.PRODUCTION_BE_PORT }}
          script: |
            docker compose --env-file ${{ secrets.ENV_FILENAME_BACKEND }} pull
            docker compose --env-file ${{ secrets.ENV_FILENAME_BACKEND }} up -d
            docker image prune -f
